$_in_10K:
    value: 0.0075
$_out_10K:
    value: 0.03
_wandb:
    value:
        cli_version: 0.21.0
        e:
            h95rh2cxoe90loi066ycs9qvn14ad4si:
                apple:
                    ecpuCores: 4
                    gpuCores: 30
                    memoryGb: 36
                    name: Unknown
                    pcpuCores: 10
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "3221225472"
                args:
                    - --csv-file
                    - examples_csv/tiny.csv
                    - --provider
                    - openrouter
                    - --run-name
                    - tiny_csv_test
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "729139810304"
                email: diego@gainforest.net
                executable: /Users/DiegoRB/Desktop/deepgov_pipeline/t3c_python/venv/bin/python
                host: MacBook-Pro-de-Dra.local
                memory:
                    total: "38654705664"
                os: macOS-15.5-x86_64-i386-64bit-Mach-O
                program: /Users/DiegoRB/Desktop/deepgov_pipeline/t3c_python/main.py
                python: CPython 3.13.5
                root: /Users/DiegoRB/Desktop/deepgov_pipeline/t3c_python
                startedAt: "2025-07-16T16:05:01.873185Z"
                writerId: h95rh2cxoe90loi066ycs9qvn14ad4si
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 95
            "2":
                - 95
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-x86_64
base_url:
    value: https://openrouter.ai/api/v1
cost_guess:
    value: 0.011676754000908217
model:
    value: google/gemini-2.0-flash-001
provider:
    value: OpenRouter (Gemini 2.0 Flash)
use_openrouter:
    value: true
